pdk update + unit test/linting fixes
indiana-university/puppet-duo_unix pull request #46
Opened 2024-05-01 15:18 UTC by markaddonizio

Update to pdk 3.0.1; unit test and syntax fixes.

2024-05-01 15:51 UTC, thoughtful-explorer requested changes

2024-05-01 15:51 UTC, thoughtful-explorer commented on .gitignore
This .config dir doesn't look like it's doing anything but puppet analytics - did something come up in testing that required this? I'd otherwise recommend continuing to ignore it

2024-05-01 15:51 UTC, thoughtful-explorer commented on .pdkignore
the .github dir seems like a personalization to me - any real reason to keep this in version control?

2024-05-01 15:51 UTC, thoughtful-explorer commented on .vscode/extensions.json
Looks like another personalization - recommend not version controlling this

2024-05-01 15:51 UTC, thoughtful-explorer commented on .vscode/extensions.json
Or making a note about it in README for vscode users

2024-05-01 15:51 UTC, thoughtful-explorer commented on Rakefile
Is this functionality you replaced with that Shopify.ruby-lsp vscode extension?

2024-05-01 15:51 UTC, thoughtful-explorer commented on Gemfile
Is this functionality you replaced with that Shopify.ruby-lsp vscode extension?

2024-05-01 15:51 UTC, thoughtful-explorer commented on manifests/init.pp
I could imagine being scolded by a linter for adding an extra space like that in the newly added line 144 - are you sure the old line 145 isn't correct?

2024-05-01 15:51 UTC, thoughtful-explorer commented on manifests/pam_ssh_config.pp
Are you sure on the extra space here for line 31?

2024-05-01 18:28 UTC, markaddonizio commented on manifests/init.pp
We're actually being scolded by the pdk validate linter for not having it.  Puppet syntax guidelines ask that the `=>` arrows all line up per block.

2024-05-01 18:28 UTC, markaddonizio commented on manifests/pam_ssh_config.pp
More puppet wanting aligned arrows (=>).

2024-05-01 18:35 UTC, markaddonizio commented on Rakefile
This was the result of running 'pdk update' and letting it automatically make "relevant" changes.

I found a discussion of the shopify lsp (the discussion mentions spotify, but links to shopify): https://github.com/puppetlabs/pdk/discussions/1340

Trying to dig through pdk commits for justifications on the rest of the changes.

2024-05-01 19:24 UTC, markaddonizio commented on .gitignore
https://www.puppet.com/docs/pdk/2.x/pdk_creating_modules.html

We seemingly created our module using the default template, so every time we run pdk update, it checks here: https://github.com/puppetlabs/pdk-templates (config-defaults.yml maybe?) for what to change.

2024-05-03 17:01 UTC, thoughtful-explorer commented on .gitignore
I can't find any more puppet modules that have the .config directory at all, let alone having it in .gitignore. I still propose keeping it in .gitignore. Another point of trivia here is that PDK itself ignores that directory: https://github.com/puppetlabs/pdk/blob/main/.gitignore

2024-05-03 17:04 UTC, thoughtful-explorer commented on Rakefile
Were you unable to do the pdk stuff you needed to do without updating? This kind of begs the question of whether we should update our puppet server by a major version. Should we do it because it's probably a good idea? Or should we take the "well, if it ain't broke..." approach? What do you see if you do a pdk --version in your testing environment? I see 3.0.1

2024-05-03 17:05 UTC, thoughtful-explorer commented on manifests/init.pp
haha welp! ¯\_ (ツ)_/¯

2024-05-03 17:05 UTC, thoughtful-explorer commented on manifests/pam_ssh_config.pp
¯\_ (ツ)_/¯

2024-05-03 19:51 UTC, markaddonizio commented on .gitignore
Added .config back in, and told pdk to stop updating this file for us in .sync.yml

2024-05-03 19:56 UTC, markaddonizio commented on .pdkignore
This file is used when we run pdk build, so having it version controlled ensures we're all building the same version of the package for forge (or acceptance testing), and theoretically not bundling extranneous files into the package.

I'm ok with letting the pdk community determine the contents of this whenever we do a pdk update.  (At least for now... maybe we add this to .sync.yml in the future.)

2024-05-03 19:57 UTC, markaddonizio commented on .vscode/extensions.json
Yup.  Removed from version control, added to .gitignore, and asking .sync.yml to not manage it.

2024-05-03 19:57 UTC, markaddonizio commented on Rakefile
I kept getting the augeas gem error, and couldn't seem to reslove it.  Running pdk update did solve it though.  (And brought in all the other 'odd' changes.)

2024-05-04 02:36 UTC, thoughtful-explorer commented on .pdkignore
My mistake, sorry. I got some more context now - [I see what it's for](https://github.com/voxpupuli/puppet-mongodb/tree/master/.github). I don't think it really matters either way what pdk thinks about .github because pdk likely ignores that directory anyway but it's probably not worth putting it in .pdkignore after all even if it wouldn't hurt anything.

2024-05-06 16:18 UTC, thoughtful-explorer commented on .gitignore
I finally actually tried this in my environment instead of just armchair commenting, and all my comments about .gitignore, .pdkignore, and .vscode seem less relevant. My environment definitely wanted all these things when I performed a `pdk update` too, and I also notice them here [https://github.com/search?q=org%3Avoxpupuli%20vscode&type=code](https://github.com/search?q=org%3Avoxpupuli%20vscode&type=code), namely in [voxpupuli's puppet-augeas module](https://github.com/voxpupuli/puppet-augeas/tree/master). My apologies for the wild goose chase - I'm a bit hawkish on keeping unnecessary things in version control but seeing it appear in another reputable module's repo helps me chill out on that.

2024-05-06 16:18 UTC, thoughtful-explorer commented on .vscode/extensions.json
I finally actually tried this in my environment instead of just armchair commenting, and all my comments about .gitignore, .pdkignore, and .vscode seem less relevant. My environment definitely wanted all these things when I performed a `pdk update` too, and I also notice them here [https://github.com/search?q=org%3Avoxpupuli%20vscode&type=code](https://github.com/search?q=org%3Avoxpupuli%20vscode&type=code), namely in [voxpupuli's puppet-augeas module](https://github.com/voxpupuli/puppet-augeas/tree/master). My apologies for the wild goose chase - I'm a bit hawkish on keeping unnecessary things in version control but seeing it appear in another reputable module's repo helps me chill out on that.

2024-05-06 16:18 UTC, thoughtful-explorer approved these changes
I finally actually tried this in my environment instead of just armchair commenting, and all my comments about .gitignore, .pdkignore, and .vscode seem less relevant. My environment definitely wanted all these things when I performed a `pdk update` too, and I also notice them here [https://github.com/search?q=org%3Avoxpupuli%20vscode&type=code](https://github.com/search?q=org%3Avoxpupuli%20vscode&type=code), namely in [voxpupuli's puppet-augeas module](https://github.com/voxpupuli/puppet-augeas/tree/master). My apologies for the wild goose chase - I'm a bit hawkish on keeping unnecessary things in version control but seeing it appear in another reputable module's repo helps me chill out on that.

2024-05-06 16:19 UTC, merged